name: example
description: Example Flutter app demonstrating flutter_flavor_orchestrator usage.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_flavor_orchestrator:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/dev/
    - assets/staging/
    - assets/production/
